---
  hosts: all 
  tasks:
  - name: add external bash script
    blockinfile:        # insert multiple line to file using 'blockinfile'
      state: present
      insertafter: EOF
      dest: /etc/test/file
      marker: "<!-- add script ANSIBLE MANAGED BLOCK -->"
      content: |
        gfdgfdgfd
        lggfdggdfg
        gfdgdfgdfgdfgfdgfdgfdgfdgdffdgline 3
