---
- hosts: all 
  #become_method: sudo
  become: yes
  become_user: root
  #remote_user: ansible
  #gather_facts: false
  tasks:
    - name: Create a New file in the following directory 
      file:
        path: /var/log/bash_eternal_history
        attr: +a
        state: touch
        owner: root
        group: root
        mode:  0777
