---
- hosts: all 
  become_user: root
  tasks:
  - name: test transfer
    copy:
      src: /tmp/testfile
      dest: /home/achad
      remote_src: yes
      when: "{{ inventory_hostname == 'linux1' }}"
      owner: achad
      group: achad
      mode: '0644'
    delegate_to: all
