---
- hosts: all 
  become_user: root
  tasks:
  - name: copy mfa file to user
    copy:
      src: /var/lib/awx/projects/tmp/achad_.auth
      dest: /home/achad/.google_authenticator
      owner: achad
      group: achad
      mode: '0400'
