---
- hosts: all 
  become_user: root
  tasks:
  - name: prompt user for google-authenticator
    copy:
      src: /home/{{ item }}/.google-authenticator
      dest: /home/{{ item }}/.google-authenticator
      remote_src: true
    with_items: 
      - achad
