---
- hosts: all 
  become_user: root
  tasks:
  - name: test transfer
    copy:
      src: testfile
      dest: /home/achad
      remote_src: yes
      owner: achad
      group: achad
      mode: '0644'
