---
- hosts: all 
  become_user: root
  tasks:
  - name: prompt user for google-authenticator
    copy:
      src: /home/achad/.google_authenticator
      dest: /home/achad/.google_authenticator
      remote_src: true
