---
- hosts: all 
  #become: true
  #remote_user: tony
  tasks:
    - name: create a file
      file:
        path: /tmp/ali/file-test-playbook-1
        state: touch
        #state: directory
        owner: root
        group: root
        mode: 0777
