---
- name: Create New Users
  hosts: all
  #become: yes
  #become_method: sudo
  #become_user: root
  #remote_user: ansible
  #gather_facts: false
  #vars_files:
   # - my_vault_create_user.yml
  tasks:
    - name: Create Users
      user:
        name: "{{ user }}"  
        groups: wheel
        #script: hello.sh
        #password: "{{ my_password | password_hash('sha512') }}"
        shell: /bin/bash
        #update_password: on_create    #to avoid updating password hash in /etc/shadow
     # loop:
      # - alice
      # - vincent
    - name: Create a 2048-bit SSH key for user jsmith in ~jsmith/.ssh/id_rsa
      ansible.builtin.user:
        name: "{{ user }}" 
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
        
    - name: Copy .ssh/id_rsa.pub >> .ssh/authorized_keys
      ansible.builtin.copy:
        src: "{{ user }}"/.ssh/id_rsa.pub 
        dest: "{{ user }}"/.ssh/authorized_keys
        owner: "{{ user }}" 
        group: "{{ user }}" 
        mode: '0700'
