---
- hosts: all
  become_user: root
  tasks:
    - name: Delete Users
      user:
        name: "{{ user }}"
        state: absent
        remove: true  #it attempts to remove directories associated with the user. uncomment this if you want to remove the dir as well
