---
- hosts: all 
  become_user: root
  tasks:
  - name: edit /etc/ssh/sshd_config
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^PermitRootLogin yes'
      line: 'PermitRootLogin no'
  - name: restart sshd
    service: 
      name: sshd
      state: restarted 
