---
- hosts: all 
  become_user: root
  tasks:
  - name: prompt user for google-authenticator
    blockinfile:        # insert multiple line to file using 'blockinfile'
      state: present
      insertafter: EOF
      lineinfile: dest=/home/{{ item }/.bash_profile
      with_items:
        - user1
        - user2
       marker: "# {mark} ANSIBLE MANAGED BLOCK"
      content: |
        # Not running bash?
        google-authenticator -t -d -f -r 3 -R 30 -W
