---
- hosts: all 
  become_user: root
  tasks:
  - name: prompt user for google-authenticator
    lineinfile: 
      insertafter: EOF
      line: google-authenticator -t -d -f -r 3 -R 30 -W
      path: /home/{{ item }}/.bash_profile
    with_items:
       - user1
