---
- hosts: all 
  become_user: root
  tasks:
  - name: prompt user for google-authenticator
    lineinfile: 
      linsertafter: EOF 
      path: /home/{{ item }/.bash_profile
    with_items:
      - user1
      - user2
      - user3
      line: google-authenticator -t -d -f -r 3 -R 30 -W
