---
- hosts: all
  tasks:
    - name: Transfer file from devops-box (linux2) to linux101 (linux2)
      synchronize:
        src: /home/{{ user }}/.ssh/id_rsa
        dest: /home/{{ user }}/.ssh/id_rsa
      delegate_to: linux2
