---
- name: Create New Users
  hosts: all
  become_user: root
  #become: yes
  #become_method: sudo
  #become_user: root
  #remote_user: ansible
  #gather_facts: false
  #vars_files:
    #- /path/to/vault/vault.yml
  tasks:
    - name: Create Users
      user:
        name: "{{ user }}"
        password: "{{ password }}"
        # python3 -c 'import crypt,getpass;pw=getpass.getpass();print(crypt.crypt(pw) if (pw==getpass.getpass("Confirm: ")) else exit())
        groups: wheel
        #script: hello.sh
        #password: "{{ my_password | password_hash('sha512') }}"
        shell: /bin/bash
        #update_password: on_create    #to avoid updating password hash in /etc/shadow
    
